version: '3.7'

services:
  # db:
  #   image: postgres:latest
  #   container_name: db
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - database_data:/var/lib/postgresql/data
  #     - ./db/init:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME?Variable not set}
  #     POSTGRES_USER: ${DATABASE_USERNAME?Variable not set}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD?Variable not set}
  #     TZ: 'Asia/Jakarta'

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    # container_name: aswindanu1437/python-flask-simple
    container_name: be
    platform: linux/amd64
    restart: unless-stopped
    # command: tail -f /dev/null
    command: sh ./start.sh
    expose:
      - 5001
    ports:
      - 5001:5000
    volumes:
      - .:/app/
    # depends_on:
    #   - db
    environment:
      DATABASE_HOST: ${DATABASE_HOST?Variable not set}
      DATABASE_PORT: ${DATABASE_PORT?Variable not set}
      DATABASE_USERNAME: ${DATABASE_USERNAME?Variable not set}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD?Variable not set}
      DATABASE_NAME: ${DATABASE_NAME?Variable not set}
      DATABASE_URL: ${DATABASE_URL?Variable not set}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY?Variable not set}

volumes:
  database_data:

networks:
    default:
        name: test