version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    # container_name: aswindanu1437/python-flask-simple
    container_name: be
    platform: linux/amd64
    restart: unless-stopped
    expose:
      - 5001
    ports:
      - 5001:5000
    volumes:
      - .:/app/
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   container_name: db
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - database_data:/var/lib/postgresql/data
  #     - ./db/init:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME?Variable not set}
  #     POSTGRES_USER: ${DATABASE_USERNAME?Variable not set}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD?Variable not set}
  #     TZ: 'Asia/Jakarta'

volumes:
  database_data:

networks:
    default:
        name: test