components:
  requestBodies:
    post_request_body:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/post'
      description: None
      required: true
    put_request_body:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/put'
      description: None
      required: true
  responses:
    get_response:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/get_response_schema'
      description: get response
    post_response:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/post_response_schema'
      description: post response
    put_response:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/put_response_schema'
      description: put response
  schemas:
    get_response_schema:
      properties:
        result:
          $ref: '#/components/schemas/result_get_response_schema'
        status:
          example: success
          type: string
      type: object
    post:
      properties:
        email_or_username:
          example: abc
          type: string
        password:
          example: password
          type: string
      type: object
    post_response_schema:
      properties:
        result:
          $ref: '#/components/schemas/result_post_response_schema'
        status:
          example: success
          type: string
      type: object
    put:
      properties:
        password:
          example: password
          type: string
      type: object
    put_response_schema:
      properties:
        result:
          $ref: '#/components/schemas/result_put_response_schema'
        status:
          example: success
          type: string
      type: object
    result_get_response_schema:
      properties:
        active:
          example: true
          type: integer
        created_at:
          example: Sat, 19 Aug 2023 17:37:02 -0000
          type: string
        email:
          example: aswindanu3@tes.io
          type: string
        exp:
          example: 1692526725
          type: integer
        fresh:
          example: false
          type: integer
        fullname:
          example: Aswindanu
          type: string
        gender:
          example: M
          type: string
        iat:
          example: 1692523125
          type: integer
        id:
          example: 7
          type: integer
        jti:
          example: 441a8e0c-b633-4f38-a331-2fdcefa9e80d
          type: string
        language_id:
          example: id
          type: string
        nbf:
          example: 1692523125
          type: integer
        phone:
          example: 627839273912
          type: string
        profile_id:
          example: 1
          type: integer
        sub:
          example: aswindanu2
          type: string
        type:
          example: access
          type: string
        updated_at:
          example: Sat, 19 Aug 2023 17:37:02 -0000
          type: string
        username:
          example: aswindanu2
          type: string
      type: object
    result_post_response_schema:
      properties:
        access_token:
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        language:
          example: id
          type: string
        profile:
          example: ADMIN
          type: string
        refresh_token:
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
      type: object
    result_put_response_schema:
      properties:
        active:
          example: true
          type: integer
        created_at:
          example: Sat, 19 Aug 2023 17:37:02 -0000
          type: string
        email:
          example: aswindanu3@tes.io
          type: string
        fullname:
          example: Aswindanu
          type: string
        gender:
          example: M
          type: string
        id:
          example: 7
          type: integer
        language_id:
          example: id
          type: string
        phone:
          example: 627839273912
          type: string
        updated_at:
          example: Sat, 19 Aug 2023 17:37:02 -0000
          type: string
        username:
          example: aswindanu2
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
info:
  description: Generated at 25/06/2024 17:23:49. This is the swagger ui based on the
    open api 3.0 specification of the Application
  title: Application
  version: 1.0.0 created by the flask swagger generator.
openapi: 3.0.1
paths:
  /:
    get:
      operationId: hello
      tags:
      - None
  /api/docs/:
    get:
      operationId: show
      tags:
      - swagger_ui
  /api/docs/dist/{filename}:
    get:
      operationId: static
      parameters:
      - description: None
        in: path
        name: filename
        required: true
        schema:
          type: string
      tags:
      - swagger_ui
  /api/docs/{path}:
    get:
      operationId: show
      parameters:
      - description: None
        in: path
        name: path
        required: true
        schema:
          type: string
      tags:
      - swagger_ui
  /api/v1/auth:
    get:
      operationId: authresource
      tags:
      - auth
    post:
      operationId: authresource
      tags:
      - auth
    put:
      operationId: authresource
      tags:
      - auth
  /api/v1/login:
    get:
      operationId: get
      responses:
        '200':
          $ref: '#/components/responses/get_response'
      security:
      - bearerAuth: []
      tags:
      - auth
    post:
      operationId: post
      requestBody:
        $ref: '#/components/requestBodies/post_request_body'
      responses:
        '200':
          $ref: '#/components/responses/post_response'
      tags:
      - auth
    put:
      operationId: put
      requestBody:
        $ref: '#/components/requestBodies/put_request_body'
      responses:
        '200':
          $ref: '#/components/responses/put_response'
      security:
      - bearerAuth: []
      tags:
      - auth
  /api/v1/refresh:
    get:
      operationId: tokenresource
      tags:
      - auth
    post:
      operationId: tokenresource
      tags:
      - auth
    put:
      operationId: tokenresource
      tags:
      - auth
  /api/v1/user:
    delete:
      operationId: userresource
      tags:
      - user
    get:
      operationId: userresource
      tags:
      - user
    post:
      operationId: userresource
      tags:
      - user
    put:
      operationId: userresource
      tags:
      - user
  /login:
    get:
      operationId: logintemplate
      tags:
      - auth
    post:
      operationId: logintemplate
      tags:
      - auth
  /weight/create:
    get:
      operationId: crudtemplate
      tags:
      - weight
    post:
      operationId: crudtemplate
      tags:
      - weight
  /weight/detail:
    get:
      operationId: detailtemplate
      tags:
      - weight
  /weight/edit:
    get:
      operationId: edittemplate
      tags:
      - weight
    post:
      operationId: edittemplate
      tags:
      - weight
  /weight/home:
    get:
      operationId: hometemplate
      tags:
      - weight
servers:
- url: /
